import Head from 'next/head'
export default function Contact() {
    return (<>
        <Head>
            <title>David Adewole</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="ont-body bg-slate-100 min-h-screen pb-8">
            <div className="flex flex-col items-center pt-10">
                <h1 className="mb-6 text-3xl font-semibold">Contact</h1>
                <p className="font-light mb-6">Reach out to me 24/7</p>
            </div>
            <div className="flex flex-col justify-center items-center text-3xl font-semibold">
                <div className="mt-8 mb-8">adeoluwadavid@gmail.com</div>
                <div>+2348102395070</div>
            </div>
        </div>
    </>
    )
}