import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="font-body">
      <Head>
        <title>David Adewole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-slate-100">
        <div className="">
          <div>
            <Image src="/Adewole.jpg" alt="Logo" width={200} height={100} />
          </div>
          <h2>David Adewole</h2>
          <p>Developer Portfolio</p>
          <p>
            Hi I&apos;m David. I&apos;m a Nigerian developer who loves to solve
            problems through programming and learning new things.
          </p>
        </div>
        <div>
          <div>
            <Image src="/project.png" alt="Logo" width={200} height={100} />
            <p>Projects</p>
          </div>
          <div>
            <Image src="/github-logo.png" alt="Logo" width={200} height={100} />
            <p>Github</p>
          </div>
          <div>
            <Image src="/skills.png" alt="Logo" width={200} height={100} />
            <p>Skills</p>
          </div>
        </div>
      </div>
    </div>
  );
}
